const mongoose = require('mongoose');

const projectSchema = new mongoose.Schema(
  {
    // Who created this project
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // Basic info
    title: {
      type: String,
      required: [true, 'Project title is required'],
      trim: true,
      maxlength: 200,
    },
    description: {
      type: String,
      required: [true, 'Project description is required'],
      trim: true,
      maxlength: 2000,
    },

    // Tech stack (array of strings like "React", "Python", etc.)
    techStack: {
      type: [String],
      default: [],
    },

    // Optional template used during manual project creation
    templateType: {
      type: String,
      enum: ['', 'ML Project', 'Web App', 'Mobile App'],
      default: '',
    },

    // Roles the project still needs for matching and team formation
    requiredRoles: {
      type: [String],
      default: [],
    },

    // Starter checklist generated by template selection
    starterTasks: {
      type: [String],
      default: [],
    },

    // Starter milestones generated by template selection
    starterMilestones: {
      type: [String],
      default: [],
    },

    // Target team size used by matching and invitation workflows
    targetTeamSize: {
      type: Number,
      default: 1,
      min: 1,
    },

    // Suggested datasets (array of strings)
    datasets: {
      type: [String],
      default: [],
    },

    // Kaggle dataset links (saved by user after searching)
    datasetLinks: [
      {
        name: { type: String },
        url:  { type: String },
        size: { type: String, default: '' },
      },
    ],

    // Difficulty level
    difficulty: {
      type: String,
      enum: ['Beginner', 'Intermediate', 'Advanced'],
      default: 'Beginner',
    },

    // Estimated duration (e.g. "4-6 weeks")
    estimatedDuration: {
      type: String,
      default: '',
    },

    // Challenges / limitations
    challenges: {
      type: [String],
      default: [],
    },

    // Possible improvements / extensions
    improvements: {
      type: [String],
      default: [],
    },

    // Team members (array of user references)
    teamMembers: [
      {
        user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        role: { type: String, default: 'Member' },  // e.g. "Owner", "Member"
        joinedAt: { type: Date, default: Date.now },
      },
    ],

    // Project status
    status: {
      type: String,
      enum: ['open', 'in-progress', 'completed'],
      default: 'open',
    },

    // Category / tags for filtering
    category: {
      type: String,
      enum: ['', 'AI', 'Web', 'Mobile', 'Data Science', 'Hardware', 'Design', 'Other'],
      default: '',
    },

    // GitHub repository URL (e.g. https://github.com/user/repo)
    githubRepo: {
      type: String,
      default: '',
      trim: true,
    },

    // Project resources (links, docs, references)
    resources: [
      {
        title: { type: String, required: true, trim: true },
        url:   { type: String, required: true, trim: true },
        type:  { type: String, enum: ['Documentation', 'Design', 'Research', 'Tutorial', 'API', 'Other'], default: 'Other' },
        addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        addedAt: { type: Date, default: Date.now },
      },
    ],
  },
  {
    timestamps: true,
  }
);

// Text index for search by title and description
projectSchema.index({ title: 'text', description: 'text' });
projectSchema.index({ createdBy: 1, status: 1 });
projectSchema.index({ templateType: 1, category: 1 });
projectSchema.index({ requiredRoles: 1 });

module.exports = mongoose.model('Project', projectSchema);
